
sources:
  - name: dev_bronze
    description: An input layer. The store of all raw data, exactly as received from the sources, one table per source.
                It has meaning on its own. Everything is stored as text and almost nothing is asserted about it.
                The only exception is for columns starting with "meta_", which must not be null.
                meta_ columns store metadata created at ingestion.
    tables:
      - name: brnz_journal_entries
        description: csv data coming from the app "edenic" developed by bluelab.
  - name: dev_corrections
    description: An input layer. The store of all corrections, as uploaded by reviewers from external tools (for example excel).
                It has meaning only for journal entries already in the warehouse.
    tables:
      - name: corr_journal_entries