
sources:
  - name: dev_bronze
    description: The layer that It stores raw, uncleaned data, as provided by the external source. one table per source. 
                almost no assertion is based about this layer, as it is very permissive in the data it accepts.
                the only exception is for columns starting with "meta_" that must not be null.
                meta_ columns store metadata created at ingestion.
    tables:
      - name: brnz_journal_entries
        description: csv data coming from the app "edenic" developed by bluelab.
  - name: dev_corrections
    description: It stores corrections made with external tools (for example excel)
    tables:
      - name: corr_journal_entries